site_name: JavaWebStack Docs
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
theme:
  name: material
  logo: 'assets/img/icon-dark.svg'
  favicon: 'assets/img/icon-dark.svg'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
copyright: '<a href="/legal-notice">Legal Notice</a><br><br>'
nav:
  - Home: index.md
  - Framework:
    - 'framework/index.md'
    - 'framework/model-binding.md'
    - 'framework/modules.md'
    - ORM:
      - 'framework/orm/index.md'
      - 'framework/orm/getting-started.md'
      - 'framework/orm/config.md'
      - 'framework/orm/query-dsl.md'
      - 'framework/orm/dates.md'
      - 'framework/orm/table-and-column-options.md'
      - 'framework/orm/observer.md'
      - 'framework/orm/soft-deletes.md'
      - 'framework/orm/type-mapping.md'
      - 'framework/orm/migrations.md'
    - HTTP-Server:
      - 'framework/httpserver/index.md'
      - 'framework/httpserver/controller.md'
      - 'framework/httpserver/middleware.md'
      - 'framework/httpserver/route-parameters.md'
      - 'framework/httpserver/response-transformer.md'
      - 'framework/httpserver/websocket.md'
      - 'framework/httpserver/testing.md'
    - Injector:
      - 'framework/injector/index.md'
      - 'framework/injector/reference.md'
    - Validator:
      - 'framework/validator/index.md'
    - Command:
      - 'framework/command/index.md'
  - HTTP-Client:
    - 'httpclient/index.md'
    - 'httpclient/reference.md'
    - 'httpclient/api-client.md'
