name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t docker.javawebstack.org/javawebstack/docs:latest .
    -
      name: Login to Nexus
      uses: docker/login-action@v1 
      with:
        registry: docker.javawebstack.org
        username: ${{ secrets.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_PASSWORD }}
    - name: Push the Docker image
      run: docker push docker.javawebstack.org/javawebstack/docs:latest
